const DEFAULT_DATA_FILENAME = 'db'
const DEFAULT_DATA_DIRECTORY_NAME = './data/'
const DEFAULT_DATA_FILENAME_URI = DEFAULT_DATA_DIRECTORY_NAME + DEFAULT_DATA_FILENAME
const DEFAULT_DATA_FILE_VALUE = '{}'

const constants = {
  DEFAULT_DATA_DIRECTORY_NAME,
  DEFAULT_DATA_FILE_VALUE,
  DEFAULT_DATA_FILENAME_URI,
}

export default constants
